---

- name: install postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
    
- name: download barman repo file
  get_url:
    url: https://dl.2ndquadrant.com/default/release/get/11/rpm
    dest: /tmp/barman-repo.sh
    mode: 0550

- name: install barman repo
  shell: /tmp/barman-repo.sh
  args:
    creates: /etc/yum.repos.d/2ndquadrant-dl-default-release-pg11.repo

- name: install postgresql server barman-cli
  yum:
    name: 
      - postgresql11-server
      - barman-cli
    state: present

- name: init db
  shell: /usr/pgsql-11/bin/postgresql-11-setup initdb
  args:
    creates: /var/lib/pgsql/11/data/postgresql.conf
    
- name: remove pgdata
  file:
    path: "/var/lib/pgsql/11/data"
    state: absent

- name: create new pgdata
  file:
    path: "/var/lib/pgsql/11/data"
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: copy base from master to slave
  become_user: postgres
  command: "pg_basebackup -X stream -h master -D /var/lib/pgsql/11/data/ -P -U streaming_user"
  notify: restart postgresql

- name: copy recovery config to slave
  copy:
    src: recovery.conf
    dest: /var/lib/pgsql/11/data/recovery.conf
    owner: postgres
    group: postgres
  notify: restart postgresql
