---
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./logs:/etc/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php:/var/www/html:rw
    depends_on:
      - fpm

  fpm:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html





...
