---
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./logs:/etc/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php:/var/www/html:rw
    depends_on:
      - fpm
      - ruby
      - go
  fpm:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html
  ruby:
    image: ruby:latest
    ports:
      - 9001:9001
    volumes:
      - ./ruby:/app

      



...
