---
version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx.conf/
      - ./php:/code
    command: [nginx, '-g', 'daemon off;']
    links:
      - fpm
    networks:
      - otus_net

  fpm:
    image: php:fpm
    volumes:
      - ./php:/code
    command: ["php", "./index.php"]
    networks:
      - otus_net

networks:
  otus_net:
    driver: bridge

...
