---
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx.conf/:ro
      - ./php:/var/www/html:rw
    command: [nginx, '-g', 'daemon off;']
    depends_on:
            - frm

  fpm:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html





...
