---
version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./logs:/etc/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf/
      - ./php:/var/www:rw
    links:
      - fpm
    networks:
      - otus_net

  fpm:
    image:
    volumes:
      - ./php:/var/www:rw
    networks:
      - otus_net

networks:
  otus_net:
    driver: bridge

...
