---
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./logs:/etc/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php:/var/www/html:rw
    depends_on:
      - fpm
      - ruby
      - go
  fpm:
    image: php:7-fpm
  ruby:
    build: ./ruby
  go:
    buld: ./go


      



...
