---
- hosts: ipaserver
  become: yes
  tasks:
  - name: Set hostname
    hostname: name=ipaserver.otus.local
  roles:
   - freeipa-server

- hosts: ipaclient 
  become: yes
  tasks:
  - name: Set hostname
    hostname: name=ipaclient.otus.local
  roles:
   - freeipa-client
