---
- name: Install docker docker-compose
  hosts: docker
  become: true
  tasks:
    - name: install docker
      yum:
        name: docker
        state: present
    - name: docker is started and runs at startup
      service:
        name: docker
        state: started
        enabled: yes
    - name: install epel-release
      yum:
        name: epel-release
        state: present
    - name: install python-pip
      yum:
        name: python-pip
        state: latest
    - name: update python-pip
      pip:
        name: pip
        extra_args: --upgrade
    - name: update python-pip
      pip:
        name: docker-compose
        state: latest  
