---

- name: install epel repo
  yum:
    name: epel-release
    state: present

- name: install postgresql repo
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present

- name: install postgresql client
  yum:
    name: postgresql11
    state: present

- name: install barman
  yum:
    name: barman
    state: present

- name: copy auth for barman
  copy:
    src: pgpass
    dest: /var/lib/barman/.pgpass
    mode: 0600
    owner: barman
    group: barman

- name: copy barman configuration
  copy:
    src: barman.conf
    dest: /etc/barman.conf
    mode: 0644

- name: copy backup configuration
  copy:
    src: master.conf
    dest: /etc/barman.d/master.conf
    mode: 0644
    
- name: create replication slot
  shell: barman receive-wal --create-slot master
