# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:router1 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.1', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "net1"},
                   {ip: '192.168.20.1', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "net2"},
                ]
  },
  :router2 => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.10.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "net1"},
                   {ip: '192.168.30.1', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "net3"},
                ]
  },
  :router3 => {
        :box_name => "centos/7",
        :net => [
                    {ip: '192.168.20.2', adapter: 2, netmask: "255.255.255.248", virtualbox__intnet: "net2"},
                    {ip: '192.168.30.2', adapter: 3, netmask: "255.255.255.248", virtualbox__intnet: "net3"},
                ]
  }
    
}
Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "router1"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            
          
            SHELL
        when "router2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            
           
            SHELL
        when "router3"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            
           
            SHELL
          end
      end

  end
  
  
end
