---
- name: Patroni | main | Include install tasks
  include: install.yml

- name: Patroni | main | Configure and run patroni cluster
  include: configure.yml
  tags: configure
  
- name: Patroni | configure | place bashrc file
  template:
    src: bashrc.j2
    dest: /root/.bashrc
