---

- name: Install percona repository
  yum: 
    name: "https://repo.percona.com/yum/percona-release-latest.noarch.rpm"
    state: present
    
- name: Install percona-server
  yum: 
    name: 
      - Percona-Server-server-57
    state: present
    
- name: Copy mysql configs
  copy: src={{ item }} dest=/etc/my.cnf.d/
  with_fileglob: "*.cnf"
  
- name: restart mysql
  service:
    name: mysql
    state: restarted
    enabled: yes

- name: Set temp mysql password
  shell: grep 'A temporary password is generated' /var/log/mysqld.log | awk '{print $11}' | head -1
  register: temp_password

- name: Change mysql password
  shell:
    mysql --connect-expired-password -uroot -p'{{ temp_password.stdout }}' -e 'ALTER USER USER() IDENTIFIED BY "{{ mysql_password }}"'


- name: Setup and run slave
  shell: |
    mysql \
      -uroot \
      -p'{{ mysql_password }}' \
      -e 'CHANGE MASTER TO \
        MASTER_HOST="192.168.11.150", \
        MASTER_USER="{{ replication_user }}", \
        MASTER_PASSWORD="{{ replication_password }}", \
        MASTER_AUTO_POSITION=1;'
    mysql \
      -uroot \
      -p'{{ mysql_password }}' \
      -e 'START SLAVE;'
