---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Add records to /etc/hosts
    lineinfile:
      path: /etc/hosts
      state: present
      line: |
        192.168.1.10 server.otus.local
        192.168.1.20 client.local  
  - name: Enable and start firewalld
    systemd:
      name: firewalld
      enabled: yes
      state: started
  - name: Add eth1 to enternal zone
    firewalld:
      zone: internal
      interface: eth1
      state: enabled
      permanent: yes
      immediate: yes
  - name: add services to firewall to internal zone
    firewalld:
      service: "{{ item }}"
      permanent: yes
      state: enabled
      zone: internal
    with_items:
      - nfs
      - rpc-bind
      - mountd
  - name: restart firewall
    service: 
      name: firewalld
      state: restarted


- hosts: server
  become: True
  roles:
    - server


- hosts: client
  become: True
  roles:
    - client
