# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end
  config.vm.define "server" do |web|
    ns.vm.network "private_network", ip: "192.168.1.10", virtualbox__intnet: "local"
    server.vm.hostname = "server"
  end
  config.vm.define "client" do |client|
    client.vm.network "private_network", ip: "192.168.1.20", virtualbox__intnet: "local"
    client.vm.hostname = "client.otus.test"
  end

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

end
