---
- name: install nfs
  yum:
    name: nfs-utils
    state: present
- name: create mount dir
  file:
    path: /mnt/nfs
    state: directory
    mode: 0777
- name: mount nfs share
  mount:
    path: /mnt/nfs
    src: server.otus.local:/var/nfs
    fstype: nfs
    opts: auto,x-systemd.automount,x-systemd.device-timeout=10,timeo=14,vers=3
    state: mounted  
