---

- name: Modification /etc/hosts
  copy:
    src: hosts
    dest: /etc/

- name: install FreeIPA-Client 
  yum: 
    name: "ipa-client" 
    state: latest 

- name: add client to domain
  ignore_errors: True
  register: result
  command: ipa-client-install  --mkhomedir --server={{ server }} --domain={{ domain }}  --realm={{ realm }} --principal={{ admin }} --password={{ password }} --force-ntpd --unattended

...
