---

- name: Modification /etc/hosts
  copy:
    src: hosts
    dest: /etc/

- name: install FreeIPA-Client 
  yum: 
    name: "ipa-client" 
    state: latest 

- name: add client to domain
  ignore_errors: True
  register: result
  shell: ipa-client-install -U --mkhomedir --force-ntpd --domain={{ domain }} --server={{ server }} --realm={{ realm }} --principal={{ admin }} --password={{ password }}

