---
- name: DZ11
  hosts: dz11
  become: true
  tasks:
    - name: create group "admin"
      group: 
        name: admin
        state: present
    
    - name: root to group "admin"
      user:
        name: root 
        append: yes
        groups: admin

    - name: vagrant to group "admin"
      user:
        name: vagrant
        append: yes
        groups: admin
    
    - name: create testadmin admin user
      user:
        name: "testadmin"
        password: 'testadmin' 
        state: present
        update_password: on_create
        append: yes
        groups: admin

    - name: create test non-admin user
      user:
        name: "test"
        password: 'test' 
        state: present
        update_password: on_create

    - name: epel-release install
      yum:
        name: epel-release
        state: present

    - name: pam_script install
      yum:
        name: pam_script
        state: present

    - name: script provision from template
      template:
        backup: true
        owner: root
        group: wheel
        src: "pam.sh.j2"
        dest: "/etc/pam.sh"
        mode: a+x
  
    - name: insert a new rule after an existing rule
      pamd:
        name: password-auth
        type: account
        control: required
        module_path: pam_unix.so
        new_type: account
        new_control: required
        new_module_path: pam_script.so
        module_arguments: ['/etc/pam.sh']
        state: after
   
    - name: permit ssh with password
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
        state: present
        notify: 
          - restart_sshd
  
  handlers:
     - name: restart_sshd
       systemd:
         name: sshd
         state: restarted
...
