---
- name: DZ11
  hosts: dz11
  become: true
  
  vars:
    pass_test: "test"
  
  tasks:
    - name: create group "admin"
      group: 
        name: admin
        state: present
    
    - name: root to group "admin"
      user:
        name: root 
        append: yes
        groups: admin

    - name: vagrant to group "admin"
      user:
        name: vagrant
        append: yes
        groups: admin
    
    - name: create testadmin admin user
      user:
        name: "testadmin"
        password: "{{ pass_test | password_hash('sha512') }}"  
        state: present
        update_password: on_create
        append: yes
        groups: admin

    - name: create test non-admin user
      user:
        name: "test"
        password: "{{ pass_test | password_hash('sha512') }}"
        state: present
        update_password: on_create

    - name: epel-release install
      yum:
        name: epel-release
        state: present

    - name: pam_script install
      yum:
        name: pam_script
        state: present

    - name: cope script 
      copy:
        backup: true
        owner: root
        group: wheel
        src: "pam.sh"
        dest: "/etc/pam-script.d/pam_script_acct"
        mode: a+x
  
   # - name: insert a new rule after an existing rule
    #  pamd:
     #  name: password-auth
     #  type: account
     #  control: required
     #  module_path: pam_unix.so
      #  new_type: account
      #  new_control: required
      #  new_module_path: pam_script.so
     #   module_arguments: ['/etc/pam-script.d/pam_script_acct, onerr=fail']
     #   state: after
   
    - name: permit ssh with password
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication no'
        line: 'PasswordAuthentication yes'
        state: present
      notify: 
          - restart_sshd
  
  handlers:
     - name: restart_sshd
       systemd:
         name: sshd
         state: restarted
...
