---
- name: install epel-release
  yum:
    name: 
      - epel-release
    state: present
    
- name: install packages
  yum:
    name: 
      - openvpn
      - policycoreutils-python
      - easy-rsa
    state: present

- name: Change the openvpn_t server to permissive
  selinux_permissive:
    name: openvpn_t
    permissive: true
    
- name: Copy client.conf
  copy:
    src: client.conf
    dest: /etc/openvpn/client.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy ca.crt
  copy:
    src: ca.crt
    dest: /etc/openvpn/ca.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy client.crt
  copy:
    src: client.crt
    dest: /etc/openvpn/client.crt
    owner: root
    group: root
    mode: '0644'

- name: Copy client.key
  copy:
    src: client.key
    dest: /etc/openvpn/client.key
    owner: root
    group: root
    mode: '0644'


- name: Start openvpn service
  systemd:
    name: openvpn@server
    enabled: true
  notify: restart_openvpn  
...
