---
- name: Install and configure NGINX
  hosts: web
  become: true
  tasks:
    - name: install epel-release
      yum:
        name: 
        - epel-release
        state: present
    
    - name: install packages
      yum:
        name: 
        - nginx
        - policycoreutils-python
        state: present

    - name: Change the nginx_t server to permissive
      selinux_permissive:
        name: httpd_t
        permissive: true
        
    - name: Copy nginx.conf
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
  

    - name: Start nginx service
      systemd:
        name: nginx
        enabled: true 
    
    - name: restart nginx service
      systemd:
        name: nginx
        state: restarted
