# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.network "public_network", bridge: "enp5s0"
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
  end
  config.vm.define "web" do |web|
    web.vm.hostname = "web"
  end

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.become = "true"
  end

end
