---
# Prepare host
- name: Consul | Install required packages
  yum:
    name: unzip
    state: present
    

# Install consul
- include: install.yml
  tags:
    - install

- include: configure.yml
  tags:
    - config
