# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :ovpnserver => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.0.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ovpn-net"},
    ]
  },
  :ovpnclient => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.0.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "ovpn-net"},
    ]
  },
  :tap1 => {
    :box_name => "centos/7",
    :net => [
      {ip: '1922.168.1.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "tap-net"},
    ]
  },
  :tap2 => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.1.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "tap-net"},
    ]
  },
  :tun1 => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.2.1', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "tun-net"},
    ]
  },
  :tun2 => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.2.2', adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "tun-net"},
    ]
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|

      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      config.vm.provider "virtualbox" do |v|
        v.memory = 256
      end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ipconf
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when /ovpn/
        box.vm.provision "ansible" do |ansible|
          ansible.playbook = "provisioning/playbook.yml"
          ansible.become = "true"
        end
      when "tap1"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          setenforce 0
          yum install -y epel-release
          yum install -y openvpn iperf
          cp /vagrant/provisioning/tap1-server.conf /etc/openvpn/server.conf
          systemctl start openvpn@server && systemctl enable openvpn@server
          SHELL
      when "tap2"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          setenforce 0
          yum install -y epel-release
          yum install -y openvpn iperf
          cp /vagrant/provisioning/tap2-client.conf /etc/openvpn/client.conf
          systemctl start openvpn@client && systemctl enable openvpn@client
          SHELL
      when "tun1"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          setenforce 0
          yum install -y epel-release
          yum install -y openvpn iperf
          cp /vagrant/provisioning/tun1-server.conf /etc/openvpn/server.conf
          systemctl start openvpn@server && systemctl enable openvpn@server
          SHELL
      when "tun2"
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          setenforce 0
          yum install -y epel-release
          yum install -y openvpn iperf
          cp /vagrant/provisioning/tun2-client.conf /etc/openvpn/client.conf
          systemctl start openvpn@client && systemctl enable openvpn@client
          SHELL
      end
    end
  end
end
