---
- name: install epel-release
  yum:
    name: 
      - epel-release
    state: present
    
- name: install packages
  yum:
    name: 
      - openvpn
      - policycoreutils-python
      - easy-rsa
    state: present

- name: Change the openvpn_t server to permissive
  selinux_permissive:
    name: openvpn_t
    permissive: true


- name: Copy server.conf
  copy:
    src: server.conf
    dest: /etc/openvpn/server.conf
    owner: root
    group: root
    mode: '0644'
    
- name: Gen cert and keys
  shell: |
    /usr/share/easy-rsa/3/easyrsa --batch init-pki
    /usr/share/easy-rsa/3/easyrsa --batch build-ca nopass
    /usr/share/easy-rsa/3/easyrsa --batch gen-dh
    /usr/share/easy-rsa/3/easyrsa --batch gen-req server nopass
    /usr/share/easy-rsa/3/easyrsa --batch sign-req server server 
    /usr/share/easy-rsa/3/easyrsa --batch gen-req client nopass
    /usr/share/easy-rsa/3/easyrsa --batch sign-req client client
    cp /etc/openvpn/pki/ca.crt /vagrant/roles/ovpnclient/files/
    cp /etc/openvpn/pki/issued/client.crt /vagrant/roles/ovpnclient/files/
    cp /etc/openvpn/pki/private/client.key /vagrant/roles/ovpnclient/files/
  args:
    chdir: /etc/openvpn/


- name: Start openvpn service
  systemd:
    name: openvpn@server
    enabled: true
  notify: restart_openvpn  
...
