---
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./logs:/etc/logs/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php:/var/www/html:rw
    links:
      - fpm
      - ruby
      - go
    networks:
      - otus_net
  fpm:
    image: php:7-fpm
    volumes:
      - ./php:/var/www/html:rw
    networks:
      - otus_net
  ruby:
    build: ./ruby
    networks:
      - otus_net
  go:
    build: ./go
    networks:
      - otus_net
      
networks:
  otus_net:
  

      



...
