---
- name: setup master
  hosts: master
  become: True
  roles:
    - master

- name: setup slave
  hosts: slave
  become: True
  roles:
    - slave

- name: setup backup
  hosts: backup
  become: True
  roles:
    - backup
