---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Add records to /etc/hosts
    lineinfile:
      path: /etc/hosts
      state: present
      line: |
        192.168.1.10 master.otus.local
        192.168.1.20 slave.otus.local 
        192.168.1.30 backup.otus.local

- hosts: master
  become: True
  roles:
    - master


- hosts: slave
  become: True
  roles:
    - slave


- hosts: backup
  become: True
  roles:
    - backup
