---
- name: Enable and start ELK & services
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  with_items:
    - elasticsearch
    - logstash
    - filebeat
    - kibana

...
