---
# - name: Set hostname
#   hostname: name=ipaserver.otus.local

 - name: install epel-release
   yum: 
     name: epel-release 
     state: latest 

 - name: install ipa-server
   yum:
     name: ipa-server 
     state: latest 
 
 - name: install ipa-server-dns
   yum:
     name: ipa-server-dns
     state: latest

 - name: Modification /etc/hosts
   copy:
     src: hosts
     dest: /etc/

 - name: dbus service restart
   systemd:
     name: dbus.service
     state: restarted
     enabled: yes

 - name: IPA-Server install
   ignore_errors: True
   register: result
   shell: ipa-server-install -U --setup-dns --mkhomedir --hostname={{ server }} --domain={{ domain }} --realm={{ realm }} --ds-password={{ dbpassword }} --admin-password={{ password }} --setup-dns --no-forwarders --no-reverse
