# -*- mode: ruby -*-
# vi: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :client => {
        :box_name => "centos/7",
        :ip_addr => '192.168.1.101',
	      :memory => "256",
  },
  :bacula => {
        :box_name => "centos/7",
        :ip_addr => '192.168.1.102',
	      :memory => "512", 
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "public_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
	        vb.memory = boxconfig[:memory]  
          vb.name = boxname.to_s
            
        end
        
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
   SHELL
      case boxname.to_s
      when "client"
      box.vm.provision "shell", run: "always", inline: <<-SHELL
      yum install -y vim bacula-client
      SHELL

     when "bacula"
     box.vm.provision "shell", run: "always", inline: <<-SHELL
     yum install -y bacula-director-mysql bacula-storage-mysql bacula-console mariadb-server
      SHELL

end
  end
  end
end
